/**
 * DraftHistoryTimeline — FU-004
 * Timeline per draft: generated → edited → approved → sent | rejected | expired
 * Status badges and timestamps for each transition.
 */

import React from 'react';
import {
  Clock,
  Edit2,
  CheckCircle2,
  XCircle,
  Send,
  Calendar,
  Sparkles,
  AlertCircle,
} from 'lucide-react';
import { type FollowUpDraft } from '@/lib/hooks/useFollowUpDrafts';
import { cn } from '@/lib/utils';
import { format } from 'date-fns';

interface TimelineEvent {
  status: string;
  timestamp: string | null;
  label: string;
  icon: React.ReactNode;
  color: string;
}

function buildTimeline(draft: FollowUpDraft): TimelineEvent[] {
  const events: TimelineEvent[] = [
    {
      status: 'generated',
      timestamp: draft.generated_at,
      label: 'Generated by AI',
      icon: <Sparkles className="w-3.5 h-3.5" />,
      color: 'text-[#37bd7e] border-[#37bd7e]/30 bg-[#37bd7e]/10',
    },
  ];

  if (draft.status === 'editing' || draft.edited_body) {
    events.push({
      status: 'editing',
      timestamp: draft.updated_at,
      label: 'Edited',
      icon: <Edit2 className="w-3.5 h-3.5" />,
      color: 'text-blue-400 border-blue-500/30 bg-blue-500/10',
    });
  }

  if (draft.approved_at) {
    events.push({
      status: 'approved',
      timestamp: draft.approved_at,
      label: 'Approved',
      icon: <CheckCircle2 className="w-3.5 h-3.5" />,
      color: 'text-emerald-400 border-emerald-500/30 bg-emerald-500/10',
    });
  }

  if (draft.scheduled_email_id && draft.status === 'scheduled') {
    events.push({
      status: 'scheduled',
      timestamp: draft.updated_at,
      label: 'Scheduled',
      icon: <Calendar className="w-3.5 h-3.5" />,
      color: 'text-purple-400 border-purple-500/30 bg-purple-500/10',
    });
  }

  if (draft.sent_at) {
    events.push({
      status: 'sent',
      timestamp: draft.sent_at,
      label: 'Sent',
      icon: <Send className="w-3.5 h-3.5" />,
      color: 'text-gray-400 border-gray-500/30 bg-gray-500/10',
    });
  }

  if (draft.rejected_at) {
    events.push({
      status: 'rejected',
      timestamp: draft.rejected_at,
      label: 'Rejected',
      icon: <XCircle className="w-3.5 h-3.5" />,
      color: 'text-red-400 border-red-500/30 bg-red-500/10',
    });
  }

  if (draft.expires_at && draft.status === 'expired') {
    events.push({
      status: 'expired',
      timestamp: draft.expires_at,
      label: 'Expired',
      icon: <AlertCircle className="w-3.5 h-3.5" />,
      color: 'text-gray-500 border-gray-600/30 bg-gray-600/10',
    });
  }

  return events;
}

interface DraftHistoryTimelineProps {
  draft: FollowUpDraft;
}

export function DraftHistoryTimeline({ draft }: DraftHistoryTimelineProps) {
  const events = buildTimeline(draft);

  return (
    <div className="p-4">
      <p className="text-xs font-medium text-gray-400 mb-3 flex items-center gap-1.5">
        <Clock className="w-3.5 h-3.5" />
        Draft history
      </p>

      <div className="space-y-0">
        {events.map((event, index) => (
          <div key={event.status} className="flex gap-3">
            {/* Timeline line + dot */}
            <div className="flex flex-col items-center">
              <div
                className={cn(
                  'flex-shrink-0 w-6 h-6 rounded-full border flex items-center justify-center',
                  event.color
                )}
              >
                {event.icon}
              </div>
              {index < events.length - 1 && (
                <div className="w-px flex-1 bg-gray-800 mt-1 mb-1 min-h-[16px]" />
              )}
            </div>

            {/* Content */}
            <div className={cn('pb-3', index === events.length - 1 ? '' : '')}>
              <p className="text-xs font-medium text-gray-300 leading-5">{event.label}</p>
              {event.timestamp && (
                <p className="text-xs text-gray-600">
                  {format(new Date(event.timestamp), 'MMM d, yyyy HH:mm')}
                </p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
