/**
 * Edit Distance Utilities — STY-004
 *
 * Pure TypeScript Levenshtein distance computation for comparing proposal
 * sections before and after rep edits. Results flow into ApprovalEvent
 * `edit_distance` and `edit_fields` for `approved_edited` signals.
 *
 * No external dependencies — safe to import from edge functions and frontend.
 */

// =============================================================================
// Types
// =============================================================================

/** Minimal ProposalSection shape required for comparison. */
export interface ProposalSection {
  id: string
  title: string
  content: string  // HTML content
  order: number
}

export interface ProposalEditMetrics {
  /** Normalized edit distance across all sections (0 = identical, 1 = completely different). */
  overall_distance: number
  /** Per-section normalized edit distances, keyed by section id. */
  section_distances: Record<string, number>
  /** IDs of sections where edit distance > 0. */
  edited_section_ids: string[]
  /** ID of the section with the highest edit distance, or null if nothing changed. */
  most_edited_section: string | null
}

// =============================================================================
// Levenshtein implementation
// =============================================================================

/**
 * Compute the raw Levenshtein edit distance between two strings.
 *
 * Uses the standard dynamic programming approach with a two-row rolling buffer
 * to keep memory usage proportional to `min(a.length, b.length)` rather than
 * `a.length * b.length`. This is sufficient for comparing HTML content strings
 * that are typically a few hundred to a few thousand characters long.
 *
 * Time:  O(m * n)   where m = a.length, n = b.length
 * Space: O(min(m, n))
 */
function levenshtein(a: string, b: string): number {
  // Trivial cases
  if (a === b) return 0
  if (a.length === 0) return b.length
  if (b.length === 0) return a.length

  // Ensure `a` is the shorter string so the column array is smaller
  if (a.length > b.length) {
    const tmp = a
    a = b
    b = tmp
  }

  const m = a.length
  const n = b.length

  // prev[j] = edit distance between a[0..i-1] and b[0..j-1]
  let prev = new Array<number>(m + 1)
  let curr = new Array<number>(m + 1)

  for (let j = 0; j <= m; j++) prev[j] = j

  for (let i = 1; i <= n; i++) {
    curr[0] = i
    for (let j = 1; j <= m; j++) {
      const cost = b[i - 1] === a[j - 1] ? 0 : 1
      curr[j] = Math.min(
        curr[j - 1] + 1,         // insertion
        prev[j] + 1,              // deletion
        prev[j - 1] + cost,       // substitution
      )
    }
    // Swap rows
    const tmp = prev
    prev = curr
    curr = tmp
  }

  return prev[m]
}

// =============================================================================
// Public API
// =============================================================================

/**
 * Compute normalized Levenshtein distance between two strings.
 *
 * Returns a ratio from 0 (identical) to 1 (completely different).
 * Normalizes by the length of the longer string so that short strings
 * that differ by one character are weighted comparably to long strings
 * that differ by one character.
 *
 * Returns 0 when both strings are empty.
 *
 * @param original - The AI-generated string (before rep edits).
 * @param edited   - The string after the rep made changes.
 */
export function computeEditDistance(original: string, edited: string): number {
  if (original === edited) return 0

  const maxLen = Math.max(original.length, edited.length)
  if (maxLen === 0) return 0

  const raw = levenshtein(original, edited)
  return raw / maxLen
}

/**
 * Compare original and edited ProposalSection arrays.
 *
 * Sections are matched by `id`. Sections present in `editedSections` but
 * absent in `originalSections` (i.e. newly added) are treated as completely
 * new (distance 1.0). Sections present in `originalSections` but absent in
 * `editedSections` (i.e. deleted) are also treated as fully changed (distance
 * 1.0).
 *
 * The `overall_distance` is the arithmetic mean of all per-section distances,
 * giving equal weight to each section regardless of its character count.
 * This avoids long boilerplate sections (e.g. terms) dominating the score.
 *
 * @param originalSections - Sections as generated by the AI pipeline.
 * @param editedSections   - Sections after the rep made edits in the UI.
 */
export function computeProposalEditMetrics(
  originalSections: ProposalSection[],
  editedSections: ProposalSection[],
): ProposalEditMetrics {
  const originalById = new Map<string, ProposalSection>(
    originalSections.map((s) => [s.id, s]),
  )
  const editedById = new Map<string, ProposalSection>(
    editedSections.map((s) => [s.id, s]),
  )

  // Collect every unique section id across both arrays
  const allIds = new Set<string>([
    ...originalSections.map((s) => s.id),
    ...editedSections.map((s) => s.id),
  ])

  const sectionDistances: Record<string, number> = {}

  for (const id of allIds) {
    const orig = originalById.get(id)
    const edit = editedById.get(id)

    if (!orig && edit) {
      // Newly added section — fully new content
      sectionDistances[id] = 1.0
    } else if (orig && !edit) {
      // Deleted section — treat as fully changed
      sectionDistances[id] = 1.0
    } else if (orig && edit) {
      // Compare both title and content — concatenate with a separator so that
      // a title-only change still registers as a non-zero distance
      const origText = `${orig.title}\x00${orig.content}`
      const editText = `${edit.title}\x00${edit.content}`
      sectionDistances[id] = computeEditDistance(origText, editText)
    }
  }

  const distances = Object.values(sectionDistances)
  const overall_distance =
    distances.length > 0
      ? distances.reduce((sum, d) => sum + d, 0) / distances.length
      : 0

  const edited_section_ids = Object.entries(sectionDistances)
    .filter(([, d]) => d > 0)
    .map(([id]) => id)

  let most_edited_section: string | null = null
  let maxDist = 0
  for (const [id, dist] of Object.entries(sectionDistances)) {
    if (dist > maxDist) {
      maxDist = dist
      most_edited_section = id
    }
  }

  return {
    overall_distance,
    section_distances: sectionDistances,
    edited_section_ids,
    most_edited_section: maxDist > 0 ? most_edited_section : null,
  }
}
