/**
 * Landing Page Template Library
 * Pre-built templates with sections, copy, and brand config.
 * US-018 (template data), US-019 (gallery UI), US-020 (phase skip logic)
 */

import type { LandingSection, BrandConfig } from '../types';

export type TemplateCategory = 'saas' | 'agency' | 'product' | 'event' | 'waitlist' | 'portfolio';

export interface LandingTemplate {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  sectionCount: number;
  sections: LandingSection[];
  brandConfig: BrandConfig;
}

// ---------------------------------------------------------------------------
// 1. SaaS Hero — indigo/purple palette
// ---------------------------------------------------------------------------
const saasHero: LandingTemplate = {
  id: 'saas-hero',
  name: 'SaaS Hero',
  description: 'Full-featured SaaS landing page with gradient hero, problem/solution flow, features grid, social proof, pricing, and CTA.',
  category: 'saas',
  sectionCount: 7,
  sections: [
    {
      id: 't1-hero-001',
      type: 'hero',
      order: 0,
      copy: {
        headline: 'Ship faster. Scale smarter.',
        subhead: 'The all-in-one platform that replaces your entire tool stack.',
        body: 'Stop juggling 12 tabs. One workspace for your team to plan, build, and ship — with AI that actually helps.',
        cta: 'Start Free Trial',
        micro_copy: 'No credit card required',
      },
      layout_variant: 'gradient',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#312e81', text_color: '#f8fafc', accent_color: '#818cf8' },
      asset_strategy: 'image',
      divider: 'wave',
    },
    {
      id: 't1-problem-002',
      type: 'problem',
      order: 1,
      copy: {
        headline: 'Your team is drowning in tools',
        subhead: 'Context switching kills productivity',
        body: 'Every new tool adds another login, another tab, another place where information gets lost. Your team spends more time managing tools than doing actual work.',
        cta: 'See the solution',
      },
      layout_variant: 'split-left',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0f172a', text_color: '#e2e8f0', accent_color: '#f87171' },
      asset_strategy: 'svg',
      divider: 'none',
    },
    {
      id: 't1-solution-003',
      type: 'solution',
      order: 2,
      copy: {
        headline: 'One workspace. Zero friction.',
        subhead: 'Everything your team needs, unified',
        body: 'Planning, docs, tasks, chat, and AI — all in one place. No more copy-pasting between apps or losing context in handoffs.',
        cta: 'See how it works',
      },
      layout_variant: 'split-right',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1e1b4b', text_color: '#e2e8f0', accent_color: '#a78bfa' },
      asset_strategy: 'image',
      divider: 'curve',
    },
    {
      id: 't1-features-004',
      type: 'features',
      order: 3,
      copy: {
        headline: 'Built for modern teams',
        subhead: 'Every feature designed to eliminate busywork',
        body: '',
        cta: 'Explore all features',
      },
      layout_variant: 'cards-grid',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0f172a', text_color: '#e2e8f0', accent_color: '#818cf8' },
      content_blocks: [
        { type: 'bullet', label: 'AI Copilot', value: 'Draft docs, summarize threads, and automate repetitive tasks', icon: 'Sparkles' },
        { type: 'bullet', label: 'Real-time Collaboration', value: 'Work together without stepping on each other\'s toes', icon: 'Users' },
        { type: 'bullet', label: 'Integrations', value: 'Connect your existing tools with one-click setups', icon: 'Plug' },
        { type: 'bullet', label: 'Analytics', value: 'See what\'s working and where your team gets stuck', icon: 'BarChart3' },
      ],
      asset_strategy: 'icon',
      divider: 'none',
    },
    {
      id: 't1-social-005',
      type: 'social-proof',
      order: 4,
      copy: {
        headline: 'Trusted by 2,000+ teams',
        subhead: '',
        body: '',
        cta: '',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1e1b4b', text_color: '#e2e8f0', accent_color: '#a78bfa' },
      content_blocks: [
        { type: 'quote', label: 'Sarah K., Head of Product', value: 'We replaced 5 tools with this one. Our team is 40% more productive.' },
        { type: 'quote', label: 'Marcus T., CTO', value: 'The AI copilot alone saves our engineering team 10 hours a week.' },
        { type: 'stat', label: 'Teams', value: '2,000+' },
        { type: 'stat', label: 'Tasks completed', value: '5M+' },
      ],
      asset_strategy: 'none',
      divider: 'diagonal',
    },
    {
      id: 't1-pricing-006',
      type: 'pricing',
      order: 5,
      copy: {
        headline: 'Simple, transparent pricing',
        subhead: 'Start free. Scale when you are ready.',
        body: 'Free for teams up to 5. Pro at $12/user/month. Enterprise custom pricing.',
        cta: 'Start Free',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0f172a', text_color: '#e2e8f0', accent_color: '#818cf8' },
      asset_strategy: 'none',
      divider: 'none',
    },
    {
      id: 't1-cta-007',
      type: 'cta',
      order: 6,
      copy: {
        headline: 'Ready to simplify your workflow?',
        subhead: 'Join 2,000+ teams shipping faster with less friction.',
        body: '',
        cta: 'Get Started Free',
        micro_copy: '14-day free trial. No credit card required.',
      },
      layout_variant: 'gradient',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#312e81', text_color: '#f8fafc', accent_color: '#818cf8' },
      asset_strategy: 'none',
      divider: 'wave',
    },
  ],
  brandConfig: {
    primary_color: '#6366f1',
    secondary_color: '#8b5cf6',
    accent_color: '#818cf8',
    bg_color: '#0f172a',
    text_color: '#f8fafc',
    font_heading: 'Inter',
    font_body: 'Inter',
    show_dividers: true,
  },
};

// ---------------------------------------------------------------------------
// 2. Agency — slate/amber palette
// ---------------------------------------------------------------------------
const agencyPro: LandingTemplate = {
  id: 'agency-pro',
  name: 'Agency',
  description: 'Clean agency page with split hero, alternating features, logo banner, and bold CTA.',
  category: 'agency',
  sectionCount: 4,
  sections: [
    {
      id: 't2-hero-001',
      type: 'hero',
      order: 0,
      copy: {
        headline: 'We build brands that people remember',
        subhead: 'Strategy, design, and growth — end to end.',
        body: 'From early-stage startups to category leaders, we help ambitious companies stand out, convert, and scale.',
        cta: 'Book a Call',
      },
      layout_variant: 'split-left',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0f172a', text_color: '#f8fafc', accent_color: '#f59e0b' },
      asset_strategy: 'image',
      divider: 'diagonal',
    },
    {
      id: 't2-features-002',
      type: 'features',
      order: 1,
      copy: {
        headline: 'What we do',
        subhead: 'Full-stack brand and growth services',
        body: '',
        cta: 'See our work',
      },
      layout_variant: 'alternating',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1e293b', text_color: '#e2e8f0', accent_color: '#fbbf24' },
      content_blocks: [
        { type: 'bullet', label: 'Brand Strategy', value: 'Positioning, messaging, and identity that sticks', icon: 'Target' },
        { type: 'bullet', label: 'Web Design & Dev', value: 'Beautiful sites that convert visitors into customers', icon: 'Monitor' },
        { type: 'bullet', label: 'Growth Marketing', value: 'Paid, organic, and content strategies that compound', icon: 'TrendingUp' },
        { type: 'bullet', label: 'Creative Production', value: 'Video, photography, and assets at scale', icon: 'Camera' },
      ],
      asset_strategy: 'icon',
      divider: 'none',
    },
    {
      id: 't2-social-003',
      type: 'social-proof',
      order: 2,
      copy: {
        headline: 'Trusted by ambitious brands',
        subhead: '',
        body: '',
        cta: '',
      },
      layout_variant: 'logo-banner',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0f172a', text_color: '#94a3b8', accent_color: '#f59e0b' },
      content_blocks: [
        { type: 'stat', label: 'Clients', value: '120+' },
        { type: 'stat', label: 'Revenue generated', value: '$40M+' },
        { type: 'stat', label: 'NPS Score', value: '92' },
      ],
      asset_strategy: 'none',
      divider: 'curve',
    },
    {
      id: 't2-cta-004',
      type: 'cta',
      order: 3,
      copy: {
        headline: 'Let\'s build something great together',
        subhead: 'Book a free 30-minute strategy call.',
        body: '',
        cta: 'Book a Call',
        micro_copy: 'No commitment. Just a conversation.',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1e293b', text_color: '#f8fafc', accent_color: '#f59e0b' },
      asset_strategy: 'none',
      divider: 'none',
    },
  ],
  brandConfig: {
    primary_color: '#475569',
    secondary_color: '#f59e0b',
    accent_color: '#fbbf24',
    bg_color: '#0f172a',
    text_color: '#f8fafc',
    font_heading: 'Inter',
    font_body: 'Inter',
    show_dividers: true,
  },
};

// ---------------------------------------------------------------------------
// 3. Product Launch — emerald/cyan palette
// ---------------------------------------------------------------------------
const productLaunch: LandingTemplate = {
  id: 'product-launch',
  name: 'Product Launch',
  description: 'High-energy launch page with centered hero, problem/solution narrative, feature grid, and conversion CTA.',
  category: 'product',
  sectionCount: 5,
  sections: [
    {
      id: 't3-hero-001',
      type: 'hero',
      order: 0,
      copy: {
        headline: 'Meet the future of [your category]',
        subhead: 'Launching today. Available now.',
        body: 'We rebuilt [product] from the ground up. Faster, smarter, and designed for how you actually work.',
        cta: 'Get Early Access',
        micro_copy: 'Limited spots for launch pricing',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#022c22', text_color: '#f0fdf4', accent_color: '#34d399' },
      asset_strategy: 'image',
      divider: 'wave',
    },
    {
      id: 't3-problem-002',
      type: 'problem',
      order: 1,
      copy: {
        headline: 'The old way is broken',
        subhead: 'Clunky, slow, and overpriced',
        body: 'Existing solutions were built a decade ago. They are slow, bloated, and charge you for features you never use. Your team deserves better.',
        cta: '',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0f172a', text_color: '#e2e8f0', accent_color: '#f87171' },
      asset_strategy: 'svg',
      divider: 'none',
    },
    {
      id: 't3-solution-003',
      type: 'solution',
      order: 2,
      copy: {
        headline: 'Built different, on purpose',
        subhead: 'Speed, simplicity, and power — no compromise',
        body: 'We started from scratch with one goal: make the most powerful version of this tool that anyone can use in under 60 seconds.',
        cta: 'See it in action',
      },
      layout_variant: 'split-left',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#064e3b', text_color: '#f0fdf4', accent_color: '#6ee7b7' },
      asset_strategy: 'image',
      divider: 'curve',
    },
    {
      id: 't3-features-004',
      type: 'features',
      order: 3,
      copy: {
        headline: 'Everything you need, nothing you don\'t',
        subhead: '',
        body: '',
        cta: 'View full feature list',
      },
      layout_variant: 'cards-grid',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0f172a', text_color: '#e2e8f0', accent_color: '#34d399' },
      content_blocks: [
        { type: 'bullet', label: 'Lightning Fast', value: 'Sub-100ms response times on every interaction', icon: 'Zap' },
        { type: 'bullet', label: 'Smart Defaults', value: 'Works out of the box — zero configuration needed', icon: 'Settings' },
        { type: 'bullet', label: 'Team Ready', value: 'Real-time collaboration with granular permissions', icon: 'Users' },
        { type: 'bullet', label: 'API First', value: 'Build anything on top with our developer-friendly API', icon: 'Code' },
      ],
      asset_strategy: 'icon',
      divider: 'none',
    },
    {
      id: 't3-cta-005',
      type: 'cta',
      order: 4,
      copy: {
        headline: 'Be first in line',
        subhead: 'Launch pricing ends soon.',
        body: '',
        cta: 'Claim Early Access',
        micro_copy: '50% off for the first 500 users',
      },
      layout_variant: 'split-left',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#022c22', text_color: '#f0fdf4', accent_color: '#34d399' },
      asset_strategy: 'none',
      divider: 'wave',
    },
  ],
  brandConfig: {
    primary_color: '#059669',
    secondary_color: '#06b6d4',
    accent_color: '#34d399',
    bg_color: '#0f172a',
    text_color: '#f0fdf4',
    font_heading: 'Inter',
    font_body: 'Inter',
    show_dividers: true,
  },
};

// ---------------------------------------------------------------------------
// 4. Event / Webinar — rose/pink palette
// ---------------------------------------------------------------------------
const eventWebinar: LandingTemplate = {
  id: 'event-webinar',
  name: 'Event / Webinar',
  description: 'Registration-focused page with gradient hero, speaker highlights, FAQ, and urgency-driven CTA.',
  category: 'event',
  sectionCount: 5,
  sections: [
    {
      id: 't4-hero-001',
      type: 'hero',
      order: 0,
      copy: {
        headline: 'The playbook for scaling in 2025',
        subhead: 'Live webinar — March 25 at 2pm ET',
        body: 'Join the founders of [company] as they break down the exact strategies that drove 10x growth in 18 months.',
        cta: 'Reserve Your Spot',
        micro_copy: 'Free. 60 minutes. Live Q&A included.',
      },
      layout_variant: 'gradient',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#4c0519', text_color: '#fff1f2', accent_color: '#fb7185' },
      asset_strategy: 'image',
      divider: 'wave',
    },
    {
      id: 't4-features-002',
      type: 'features',
      order: 1,
      copy: {
        headline: 'What you will learn',
        subhead: '',
        body: '',
        cta: '',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1e1023', text_color: '#fce7f3', accent_color: '#f9a8d4' },
      content_blocks: [
        { type: 'step', label: 'Part 1', value: 'Finding your first 100 customers without paid ads', icon: 'Search' },
        { type: 'step', label: 'Part 2', value: 'Building a repeatable outbound system', icon: 'Mail' },
        { type: 'step', label: 'Part 3', value: 'Converting demos into closed-won deals', icon: 'CheckCircle' },
      ],
      asset_strategy: 'icon',
      divider: 'none',
    },
    {
      id: 't4-social-003',
      type: 'social-proof',
      order: 2,
      copy: {
        headline: 'Past attendees say',
        subhead: '',
        body: '',
        cta: '',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#4c0519', text_color: '#fff1f2', accent_color: '#fb7185' },
      content_blocks: [
        { type: 'quote', label: 'David L., Founder', value: 'Best webinar I attended all year. Actionable from minute one.' },
        { type: 'quote', label: 'Priya S., Head of Sales', value: 'I implemented one tactic the next day and booked 8 meetings that week.' },
        { type: 'stat', label: 'Past attendees', value: '4,500+' },
        { type: 'stat', label: 'Average rating', value: '4.9/5' },
      ],
      asset_strategy: 'none',
      divider: 'diagonal',
    },
    {
      id: 't4-faq-004',
      type: 'faq',
      order: 3,
      copy: {
        headline: 'Frequently asked questions',
        subhead: '',
        body: '',
        cta: '',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1e1023', text_color: '#fce7f3', accent_color: '#f9a8d4' },
      content_blocks: [
        { type: 'bullet', label: 'Is it really free?', value: 'Yes. No credit card, no catch. We want to share what works.' },
        { type: 'bullet', label: 'Will there be a recording?', value: 'Yes, but only for registered attendees. Sign up to get the replay link.' },
        { type: 'bullet', label: 'Who should attend?', value: 'Founders, sales leaders, and growth teams at B2B companies.' },
      ],
      asset_strategy: 'none',
      divider: 'none',
    },
    {
      id: 't4-cta-005',
      type: 'cta',
      order: 4,
      copy: {
        headline: 'Spots are limited',
        subhead: 'Register now to save your seat.',
        body: '',
        cta: 'Reserve Your Spot',
        micro_copy: 'March 25 at 2pm ET. Calendar invite sent on registration.',
      },
      layout_variant: 'gradient',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#4c0519', text_color: '#fff1f2', accent_color: '#fb7185' },
      asset_strategy: 'none',
      divider: 'wave',
    },
  ],
  brandConfig: {
    primary_color: '#e11d48',
    secondary_color: '#ec4899',
    accent_color: '#fb7185',
    bg_color: '#1e1023',
    text_color: '#fff1f2',
    font_heading: 'Inter',
    font_body: 'Inter',
    show_dividers: true,
  },
};

// ---------------------------------------------------------------------------
// 5. Waitlist — violet/fuchsia palette (minimal 3-section page)
// ---------------------------------------------------------------------------
const waitlist: LandingTemplate = {
  id: 'waitlist-minimal',
  name: 'Waitlist',
  description: 'Minimal pre-launch page with centered hero, feature teaser grid, and email capture CTA.',
  category: 'waitlist',
  sectionCount: 3,
  sections: [
    {
      id: 't5-hero-001',
      type: 'hero',
      order: 0,
      copy: {
        headline: 'Something big is coming',
        subhead: 'Be the first to know when we launch.',
        body: 'We are building the next generation of [category]. Sign up now to get early access and founder pricing.',
        cta: 'Join the Waitlist',
        micro_copy: '1,200+ people already signed up',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#2e1065', text_color: '#f5f3ff', accent_color: '#c084fc' },
      asset_strategy: 'svg',
      divider: 'wave',
    },
    {
      id: 't5-features-002',
      type: 'features',
      order: 1,
      copy: {
        headline: 'What to expect',
        subhead: '',
        body: '',
        cta: '',
      },
      layout_variant: 'cards-grid',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1e1b4b', text_color: '#e9d5ff', accent_color: '#d946ef' },
      content_blocks: [
        { type: 'bullet', label: 'AI-Powered', value: 'Intelligent automation that learns your workflow', icon: 'Sparkles' },
        { type: 'bullet', label: 'Beautiful Design', value: 'Crafted with obsessive attention to detail', icon: 'Palette' },
        { type: 'bullet', label: 'Blazing Fast', value: 'Built on modern infrastructure for instant response', icon: 'Zap' },
      ],
      asset_strategy: 'icon',
      divider: 'none',
    },
    {
      id: 't5-cta-003',
      type: 'cta',
      order: 2,
      copy: {
        headline: 'Don\'t miss the launch',
        subhead: 'Early access members get 50% off for life.',
        body: '',
        cta: 'Join the Waitlist',
        micro_copy: 'We will only email you once — on launch day.',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#2e1065', text_color: '#f5f3ff', accent_color: '#c084fc' },
      asset_strategy: 'none',
      divider: 'wave',
    },
  ],
  brandConfig: {
    primary_color: '#7c3aed',
    secondary_color: '#d946ef',
    accent_color: '#c084fc',
    bg_color: '#1e1b4b',
    text_color: '#f5f3ff',
    font_heading: 'Inter',
    font_body: 'Inter',
    show_dividers: true,
  },
};

// ---------------------------------------------------------------------------
// 6. Minimal Portfolio — neutral/stone palette
// ---------------------------------------------------------------------------
const minimalPortfolio: LandingTemplate = {
  id: 'minimal-portfolio',
  name: 'Minimal Portfolio',
  description: 'Clean personal or studio portfolio with split hero, alternating work showcase, testimonials, and contact CTA.',
  category: 'portfolio',
  sectionCount: 4,
  sections: [
    {
      id: 't6-hero-001',
      type: 'hero',
      order: 0,
      copy: {
        headline: 'Design that drives results',
        subhead: 'Product designer with 8 years of experience shipping software people love.',
        body: 'I help startups and scale-ups turn complex problems into simple, beautiful interfaces. Currently available for new projects.',
        cta: 'View My Work',
      },
      layout_variant: 'split-left',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1c1917', text_color: '#fafaf9', accent_color: '#a8a29e' },
      asset_strategy: 'image',
      divider: 'none',
    },
    {
      id: 't6-features-002',
      type: 'features',
      order: 1,
      copy: {
        headline: 'Selected work',
        subhead: '',
        body: '',
        cta: 'See all projects',
      },
      layout_variant: 'alternating',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0c0a09', text_color: '#e7e5e4', accent_color: '#78716c' },
      content_blocks: [
        { type: 'bullet', label: 'Fintech Dashboard', value: 'Redesigned the core experience — 3x increase in daily active users', icon: 'LayoutDashboard' },
        { type: 'bullet', label: 'Health App', value: 'End-to-end design for a patient management platform', icon: 'Heart' },
        { type: 'bullet', label: 'E-commerce', value: 'Checkout flow optimization that increased conversion by 28%', icon: 'ShoppingCart' },
      ],
      asset_strategy: 'image',
      divider: 'none',
    },
    {
      id: 't6-social-003',
      type: 'social-proof',
      order: 2,
      copy: {
        headline: 'What clients say',
        subhead: '',
        body: '',
        cta: '',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#1c1917', text_color: '#fafaf9', accent_color: '#a8a29e' },
      content_blocks: [
        { type: 'quote', label: 'Alex R., CEO at StartupCo', value: 'The best designer I have worked with. Thoughtful, fast, and always pushes for better.' },
        { type: 'quote', label: 'Nina P., VP Product', value: 'Turned our messy MVP into a product users actually love. Worth every penny.' },
      ],
      asset_strategy: 'none',
      divider: 'diagonal',
    },
    {
      id: 't6-cta-004',
      type: 'cta',
      order: 3,
      copy: {
        headline: 'Let\'s work together',
        subhead: 'Available for freelance and contract roles.',
        body: '',
        cta: 'Get in Touch',
        micro_copy: 'Usually responds within 24 hours.',
      },
      layout_variant: 'centered',
      image_url: null,
      image_status: 'idle',
      svg_code: null,
      svg_status: 'idle',
      style: { bg_color: '#0c0a09', text_color: '#fafaf9', accent_color: '#a8a29e' },
      asset_strategy: 'none',
      divider: 'none',
    },
  ],
  brandConfig: {
    primary_color: '#78716c',
    secondary_color: '#a8a29e',
    accent_color: '#d6d3d1',
    bg_color: '#0c0a09',
    text_color: '#fafaf9',
    font_heading: 'Inter',
    font_body: 'Inter',
    show_dividers: false,
  },
};

// ---------------------------------------------------------------------------
// Export all templates
// ---------------------------------------------------------------------------
export const LANDING_TEMPLATES: LandingTemplate[] = [
  saasHero,
  agencyPro,
  productLaunch,
  eventWebinar,
  waitlist,
  minimalPortfolio,
];
