-- Add rendered_html column to proposals table
-- Stores the generated HTML for inline preview in the progress overlay.
-- The render function writes fully branded HTML here; the pipeline writes
-- an early preview after compose (overwritten seconds later by the branded version).

ALTER TABLE proposals ADD COLUMN IF NOT EXISTS rendered_html text;

COMMENT ON COLUMN proposals.rendered_html IS 'Self-contained HTML document generated by the template engine, used for inline preview';
