-- ============================================================================
-- Migration: EOD Synthesis Schema
-- Purpose: Create user_time_preferences and eod_deliveries tables for the
--          End-of-Day Synthesis agent. Stores per-user timezone/schedule
--          preferences and the daily EOD delivery records.
-- Story: EOD-001
-- Date: 2026-02-22
-- ============================================================================

-- ============================================================================
-- TABLE: user_time_preferences (EOD-001)
-- Stores per-user timezone and scheduled delivery time preferences.
-- Used by the EOD and morning briefing agents to fire at the right local time.
-- ============================================================================

CREATE TABLE IF NOT EXISTS user_time_preferences (
  id              UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id         UUID        NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  org_id          UUID        NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  timezone        TEXT        NOT NULL DEFAULT 'America/Chicago',
  eod_time        TIME        NOT NULL DEFAULT '17:00',
  morning_time    TIME        NOT NULL DEFAULT '08:00',
  working_days    JSONB       NOT NULL DEFAULT '["Mon","Tue","Wed","Thu","Fri"]'::jsonb,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- One preferences row per user per org
  CONSTRAINT unique_user_time_preferences UNIQUE (user_id, org_id)
);

-- Fast lookup by org for cron fan-out
CREATE INDEX IF NOT EXISTS idx_user_time_preferences_org
  ON user_time_preferences (org_id, user_id);

-- Lookup by user (self-service reads)
CREATE INDEX IF NOT EXISTS idx_user_time_preferences_user
  ON user_time_preferences (user_id);

-- ============================================================================
-- RLS: user_time_preferences
-- ============================================================================

ALTER TABLE user_time_preferences ENABLE ROW LEVEL SECURITY;

-- Users can read their own preferences
DO $$ BEGIN
  CREATE POLICY "Users can read own time preferences"
ON user_time_preferences FOR SELECT
TO authenticated
USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Users can insert their own preferences
DO $$ BEGIN
  CREATE POLICY "Users can insert own time preferences"
ON user_time_preferences FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Users can update their own preferences
DO $$ BEGIN
  CREATE POLICY "Users can update own time preferences"
ON user_time_preferences FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Service role full access (cron, orchestrator)
DO $$ BEGIN
  CREATE POLICY "Service role full access to user_time_preferences"
ON user_time_preferences FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- Trigger: keep updated_at current — user_time_preferences
-- ============================================================================

CREATE OR REPLACE FUNCTION update_user_time_preferences_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_user_time_preferences_updated_at ON user_time_preferences;
CREATE TRIGGER trg_user_time_preferences_updated_at
  BEFORE UPDATE ON user_time_preferences
  FOR EACH ROW
  EXECUTE FUNCTION update_user_time_preferences_updated_at();

GRANT SELECT, INSERT, UPDATE ON user_time_preferences TO authenticated;
GRANT ALL ON user_time_preferences TO service_role;

-- ============================================================================
-- TABLE: eod_deliveries (EOD-001)
-- Stores the daily EOD synthesis delivery per user.
-- One row per (user_id, delivery_date) — unique constraint prevents duplicates.
-- JSONB columns hold the structured sections generated by the EOD agent.
-- ============================================================================

CREATE TABLE IF NOT EXISTS eod_deliveries (
  id                UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id           UUID        NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  org_id            UUID        NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
  delivery_date     DATE        NOT NULL,
  delivered_at      TIMESTAMPTZ,
  scorecard         JSONB,
  open_items        JSONB,
  tomorrow_preview  JSONB,
  overnight_plan    JSONB,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- One delivery per user per day
  CONSTRAINT unique_eod_delivery_per_day UNIQUE (user_id, delivery_date)
);

-- Fast lookup: user's recent deliveries
CREATE INDEX IF NOT EXISTS idx_eod_deliveries_user_date
  ON eod_deliveries (user_id, delivery_date DESC);

-- Org-level lookup for admin dashboards / health checks
CREATE INDEX IF NOT EXISTS idx_eod_deliveries_org_date
  ON eod_deliveries (org_id, delivery_date DESC);

-- Partial index: undelivered rows (cron retry pickup)
CREATE INDEX IF NOT EXISTS idx_eod_deliveries_pending
  ON eod_deliveries (org_id, delivery_date)
  WHERE delivered_at IS NULL;

-- ============================================================================
-- RLS: eod_deliveries
-- ============================================================================

ALTER TABLE eod_deliveries ENABLE ROW LEVEL SECURITY;

-- Users can read their own deliveries
DO $$ BEGIN
  CREATE POLICY "Users can read own eod_deliveries"
ON eod_deliveries FOR SELECT
TO authenticated
USING (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Users can insert their own deliveries
DO $$ BEGIN
  CREATE POLICY "Users can insert own eod_deliveries"
ON eod_deliveries FOR INSERT
TO authenticated
WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Users can update their own deliveries
DO $$ BEGIN
  CREATE POLICY "Users can update own eod_deliveries"
ON eod_deliveries FOR UPDATE
TO authenticated
USING (user_id = auth.uid())
WITH CHECK (user_id = auth.uid());
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Service role full access (cron, orchestrator)
DO $$ BEGIN
  CREATE POLICY "Service role full access to eod_deliveries"
ON eod_deliveries FOR ALL
TO service_role
USING (true)
WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ============================================================================
-- Trigger: keep updated_at current — eod_deliveries
-- ============================================================================

CREATE OR REPLACE FUNCTION update_eod_deliveries_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_eod_deliveries_updated_at ON eod_deliveries;
CREATE TRIGGER trg_eod_deliveries_updated_at
  BEFORE UPDATE ON eod_deliveries
  FOR EACH ROW
  EXECUTE FUNCTION update_eod_deliveries_updated_at();

GRANT SELECT, INSERT, UPDATE ON eod_deliveries TO authenticated;
GRANT ALL ON eod_deliveries TO service_role;

-- ============================================================================
-- Table and column comments
-- ============================================================================

COMMENT ON TABLE user_time_preferences IS
  'Per-user timezone and delivery time preferences for the EOD and morning briefing agents. One row per (user_id, org_id).';
COMMENT ON COLUMN user_time_preferences.timezone IS
  'IANA timezone string, e.g. "America/Chicago". Used to convert cron UTC time to local time.';
COMMENT ON COLUMN user_time_preferences.eod_time IS
  'Local time (HH:MM) at which the EOD synthesis is delivered. Default: 17:00.';
COMMENT ON COLUMN user_time_preferences.morning_time IS
  'Local time (HH:MM) at which the morning briefing is delivered. Default: 08:00.';
COMMENT ON COLUMN user_time_preferences.working_days IS
  'JSON array of working day abbreviations. Default: ["Mon","Tue","Wed","Thu","Fri"]. EOD only fires on these days.';

COMMENT ON TABLE eod_deliveries IS
  'Daily EOD synthesis delivery records. One row per (user_id, delivery_date). JSONB sections are populated by the agent-eod-synthesis edge function.';
COMMENT ON COLUMN eod_deliveries.delivery_date IS
  'Calendar date of the delivery (local date in user timezone). Unique per user — prevents double delivery.';
COMMENT ON COLUMN eod_deliveries.delivered_at IS
  'Timestamp when the message was successfully sent. NULL means pending/in-flight.';
COMMENT ON COLUMN eod_deliveries.scorecard IS
  'Today''s activity scorecard: calls, emails, meetings, deals advanced, closed-won value.';
COMMENT ON COLUMN eod_deliveries.open_items IS
  'Unresolved items detected at EOD: overdue tasks, stalled deals, unanswered emails.';
COMMENT ON COLUMN eod_deliveries.tomorrow_preview IS
  'Calendar preview for tomorrow: meetings, prep notes, suggested first action.';
COMMENT ON COLUMN eod_deliveries.overnight_plan IS
  'Suggested async actions for tonight/early morning: emails to draft, CRM updates to make.';

-- ============================================================================
-- Migration Summary
-- ============================================================================

DO $$
BEGIN
  RAISE NOTICE '';
  RAISE NOTICE '============================================================================';
  RAISE NOTICE 'Migration: 20260222600001_eod_synthesis_schema.sql';
  RAISE NOTICE '============================================================================';
  RAISE NOTICE '';
  RAISE NOTICE 'Story covered: EOD-001';
  RAISE NOTICE '';
  RAISE NOTICE 'Tables created:';
  RAISE NOTICE '  - user_time_preferences  — per-user timezone + schedule config';
  RAISE NOTICE '  - eod_deliveries         — daily EOD synthesis delivery records';
  RAISE NOTICE '';
  RAISE NOTICE 'Indexes:';
  RAISE NOTICE '  user_time_preferences:';
  RAISE NOTICE '    - idx_user_time_preferences_org   (org_id, user_id)';
  RAISE NOTICE '    - idx_user_time_preferences_user  (user_id)';
  RAISE NOTICE '  eod_deliveries:';
  RAISE NOTICE '    - idx_eod_deliveries_user_date    (user_id, delivery_date DESC)';
  RAISE NOTICE '    - idx_eod_deliveries_org_date     (org_id, delivery_date DESC)';
  RAISE NOTICE '    - idx_eod_deliveries_pending      (partial: delivered_at IS NULL)';
  RAISE NOTICE '';
  RAISE NOTICE 'Unique constraints:';
  RAISE NOTICE '  - user_time_preferences: UNIQUE (user_id, org_id)';
  RAISE NOTICE '  - eod_deliveries:        UNIQUE (user_id, delivery_date)';
  RAISE NOTICE '';
  RAISE NOTICE 'RLS:';
  RAISE NOTICE '  - authenticated: read/insert/update own rows (user_id = auth.uid())';
  RAISE NOTICE '  - service_role:  full access (cron jobs, orchestrator)';
  RAISE NOTICE '';
  RAISE NOTICE '============================================================================';
END $$;
